In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('sales_transactions.csv')

In [2]:
df.iloc[5].to_frame("sample")

                                sample
Transaction_ID               T02003704
Order_ID                      O0101852
Customer_ID                     C00959
Customer_Name               Mia Miller
Customer_Age                      42.0
Customer_Gender             Non-binary
Customer_Segment             Corporate
Order_Date                   3/27/2023
Order_Time                    10:40:05
Sales_Channel             Retail Store
Store_ID                        TOR-01
Store_Name             Toronto Central
Country                         Canada
Region                         Ontario
City                           Toronto
Product_ID                        P012
Product_Name             Ergo Footrest
Product_Category             Furniture
Product_Subcategory   Office Furniture
Quantity                             1
Unit_Price                       79.96
Discount_Percentage                  5
Sales_Amount                     75.96
Cost_Amount                      50.09
Profit                           25.87
Payment_Method              Debit Card
Order_Status                 Completed
Shipping_Method                 Pickup
Delivery_Days                      0.0
Return_Flag                         No
Return_Reason                      NaN
Sales_Representative       Noah Wilson
Promotion_Code                  SAVE10
Customer_Rating                    1.0
Inventory_Level                   35.0
Order_Year                        2023

In [38]:
#removing unnecessary columns
df2 = df[[
    'Order_ID',
    'Customer_ID',
    'Customer_Name',
    'Customer_Age',
    'Order_Date',
    'Order_Time',
    'Store_Name',
    'Country',
    'City',
    'Product_ID',
    'Product_Name',
    'Product_Category',
    'Quantity',
    'Unit_Price',
    'Discount_Percentage',
    'Sales_Amount',
    'Cost_Amount',
    'Payment_Method',
    'Sales_Representative',
    'Promotion_Code',
    'Order_Year'
]].copy()

In [50]:
df2.describe(include='all')

,order_id,customer_id,customer_name,customer_age,order_date,order_time,store_name,country,city,product_id,...,product_category,quantity,unit_price,discount_percentage,sales_amount,cost_amount,payment_method,sales_representative,promotion_code,order_year
count,18000,18000,18000,18000.000000,18000,18000,18000,18000,18000,18000,...,18000,18000.00000,18000.000000,18000.000000,18000.000000,18000.000000,18000,18000,8288,18000.000000
unique,14541,4882,1180,NaN,NaN,15201,12,6,15,28,...,7,NaN,NaN,NaN,NaN,NaN,11,16,10,NaN
top,O0107988,C02559,Unknown,NaN,NaN,12:29:48,New York Central,United States,New York,P017,...,Electronics,NaN,NaN,NaN,NaN,NaN,Credit Card,Sophia Brown,HOLIDAY20,NaN
freq,3,20,108,NaN,NaN,5,2170,7526,2156,983,...,8121,NaN,NaN,NaN,NaN,NaN,6725,1166,1396,NaN
mean,NaN,NaN,NaN,38.917944,2024-02-11 05:47:07.200000,NaN,NaN,NaN,NaN,NaN,...,NaN,2.12650,232.775236,6.254722,457.449478,366.132677,NaN,NaN,NaN,2023.566444
min,NaN,NaN,NaN,4.000000,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,-3.00000,21.390000,0.000000,16.680000,12.170000,NaN,NaN,NaN,2022.000000
25%,NaN,NaN,NaN,32.000000,2023-02-13 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,1.00000,52.957500,0.000000,78.525000,56.105000,NaN,NaN,NaN,2023.000000
50%,NaN,NaN,NaN,39.000000,2024-02-07 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,2.00000,99.845000,5.000000,168.845000,122.315000,NaN,NaN,NaN,2024.000000
75%,NaN,NaN,NaN,46.000000,2025-02-13 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,3.00000,285.782500,10.000000,472.742500,376.145000,NaN,NaN,NaN,2025.000000
max,NaN,NaN,NaN,112.000000,2025-12-31 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,11.00000,1425.090000,110.000000,14303.070000,10791.000000,NaN,NaN,NaN,2025.000000
std,NaN,NaN,NaN,10.658819,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.78469,294.249699,6.879860,857.097154,706.335962,NaN,NaN,NaN,1.118873

In [40]:
df2.shape

(18000, 21)

In [41]:
df2.columns = df2.columns.str.strip().str.lower().str.replace(" ", "_")

In [42]:
print(df.duplicated().sum())
df = df.drop_duplicates()

0

In [43]:
df = df.replace(["N/A", "NA", "null", "-", ""], np.nan)
df2.isna().sum()

order_id                   0
customer_id                0
customer_name            108
customer_age             216
order_date                 0
order_time                 0
store_name                 0
country                    0
city                       0
product_id                 0
product_name             144
product_category           0
quantity                   0
unit_price                 0
discount_percentage        0
sales_amount               0
cost_amount                0
payment_method           144
sales_representative       0
promotion_code          9712
order_year                 0
dtype: int64

In [44]:
#filling the empty cells in columns

df2["customer_name"] = df2["customer_name"].fillna("Unknown")
df2["customer_age"] = df2["customer_age"].fillna(df2["customer_age"].median())
df2["product_name"] = df2["product_name"].fillna("Unknown Product")
df2["payment_method"] = df2["payment_method"].fillna("Unknown")

In [45]:
df2.dtypes

order_id                    str
customer_id                 str
customer_name               str
customer_age            float64
order_date                  str
order_time                  str
store_name                  str
country                     str
city                        str
product_id                  str
product_name                str
product_category            str
quantity                  int64
unit_price              float64
discount_percentage       int64
sales_amount            float64
cost_amount             float64
payment_method              str
sales_representative        str
promotion_code              str
order_year                int64
dtype: object

In [ ]:
#correcting dtypes

df2["customer_age"] = df2["customer_age"].astype(int)
df2["order_date"] = pd.to_datetime(df2["order_date"])
df2["order_time"] = pd.to_datetime(df2["order_time"]).dt.time

C:\Users\user\AppData\Local\Temp\ipykernel_11724\530079630.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2["order_time"] = pd.to_datetime(df2["order_time"]).dt.time

In [53]:
#checking impossible values in numerical columns
df2.select_dtypes("number").describe()

,customer_age,quantity,unit_price,discount_percentage,sales_amount,cost_amount,order_year
count,18000.000000,18000.00000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,38.917944,2.12650,232.775236,6.254722,457.449478,366.132677,2023.566444
std,10.658819,1.78469,294.249699,6.879860,857.097154,706.335962,1.118873
min,4.000000,-3.00000,21.390000,0.000000,16.680000,12.170000,2022.000000
25%,32.000000,1.00000,52.957500,0.000000,78.525000,56.105000,2023.000000
50%,39.000000,2.00000,99.845000,5.000000,168.845000,122.315000,2024.000000
75%,46.000000,3.00000,285.782500,10.000000,472.742500,376.145000,2025.000000
max,112.000000,11.00000,1425.090000,110.000000,14303.070000,10791.000000,2025.000000

In [59]:
#checking to see why quantity has below zero values, if the main df has returning data or not

df[df["Quantity"] < 0].head(5)

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
3986,T02006553,O0103276,C04087,Theo Green,31.0,Female,Consumer,11/29/2025,9:25:49,Online,...,Shipped,Standard,6.0,No,NaN,Grace Harris,HOLIDAY20,5.0,102.0,2025
7487,T02011209,O0111209,C00483,Benjamin Wilson,30.0,Female,Small Business,2/2/2025,11:39:22,Online,...,Processing,Standard,4.0,No,NaN,David Walker,NaN,4.0,68.0,2025
12156,T02004207,O0104207,C02953,William White,48.0,Male,Corporate,1/4/2022,21:23:13,Online,...,Completed,Standard,4.0,No,NaN,Sophia Brown,SUMMER10,5.0,104.0,2022

In [60]:
df2 = df2[df2["quantity"] >= 0].copy()

In [68]:
print(df2["payment_method"].unique().tolist())
print(df2["product_category"].unique().tolist())
print(df2["sales_representative"].unique().tolist())

['Credit Card', 'Debit Card', 'paypal', 'Apple Pay', 'Cash', 'PayPal', 'Bank Transfer', 'credit card', 'Bank transfer', 'Unknown', 'DebitCard']
['Electronics', 'Office Supplies', 'Furniture', 'Appliances', 'FURNITURE', 'electronics', 'Office supplies']
['James Anderson', 'Ella Lewis', 'Liam Davis', 'Grace Harris', 'Sophia Brown', 'Noah Wilson', 'Olivia Martin', 'David Walker', 'Mia Taylor', 'Amelia Jackson', 'Henry White', 'Daniel Miller', 'Charlotte Thomas', 'Lucas Moore', 'Emma Carter', 'Michael Clark']

In [70]:
#making all lowercase for those 2 columns

df2["payment_method"] = df2["payment_method"].str.lower()
df2["product_category"] = df2["product_category"].str.lower()

In [85]:
#same order ids are not by mistake, nor duplicate orders

df2[df2["order_id"].duplicated(keep=False)].sort_values("order_id").head(4)

,order_id,customer_id,customer_name,customer_age,order_date,order_time,store_name,country,city,product_id,...,product_category,quantity,unit_price,discount_percentage,sales_amount,cost_amount,payment_method,sales_representative,promotion_code,order_year
14878,O0100002,C03975,Charlotte Baker,34,2023-11-04,19:54:47,Austin Business,United States,Austin,P017,...,office supplies,2,44.13,10,79.43,72.20,paypal,Olivia Martin,MOM15,2023
9471,O0100002,C04639,Benjamin White,38,2025-04-15,15:45:04,Munich Zentrum,Germany,Munich,P008,...,electronics,1,118.43,5,112.51,83.98,credit card,Mia Taylor,BLACKFRIDAY25,2025
2282,O0100005,C00771,Amelia King,40,2024-05-23,17:20:37,Paris Central,France,Paris,P020,...,office supplies,1,94.30,15,80.15,63.58,paypal,Henry White,BLACKFRIDAY25,2024
13893,O0100005,C02247,David Harris,36,2025-11-06,21:55:20,Vancouver West,Canada,Vancouver,P025,...,electronics,1,49.02,5,46.57,31.56,credit card,Henry White,BACK2WORK,2025

In [79]:
df2.duplicated().sum()

np.int64(0)

In [80]:
df2.isna().sum()

order_id                   0
customer_id                0
customer_name              0
customer_age               0
order_date                 0
order_time                 0
store_name                 0
country                    0
city                       0
product_id                 0
product_name               0
product_category           0
quantity                   0
unit_price                 0
discount_percentage        0
sales_amount               0
cost_amount                0
payment_method             0
sales_representative       0
promotion_code          9711
order_year                 0
dtype: int64

In [82]:
df2.info()

<class 'pandas.DataFrame'>
Index: 17997 entries, 0 to 18044
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              17997 non-null  str
 1   customer_id           17997 non-null  str
 2   customer_name         17997 non-null  str
 3   customer_age          17997 non-null  int64
 4   order_date            17997 non-null  datetime64[us]
 5   order_time            17997 non-null  object
 6   store_name            17997 non-null  str
 7   country               17997 non-null  str
 8   city                  17997 non-null  str
 9   product_id            17997 non-null  str
 10  product_name          17997 non-null  str
 11  product_category      17997 non-null  str
 12  quantity              17997 non-null  int64
 13  unit_price            17997 non-null  float64
 14  discount_percentage   17997 non-null  int64
 15  sales_amount          17997 non-null  float64
 16  cost_amount           17997 non-null  float64
 17  payment_method        17997 non-null  str
 18  sales_representative  17997 non-null  str
 19  promotion_code        8286 non-null   str
 20  order_year            17997 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(4), object(1), str(12)
memory usage: 3.0+ MB

In [86]:
#copying the cleaned table to csv

df2.to_csv("cleaned_sales.csv", index=False)