In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('ready_housesales_data.csv')

In [ ]:
"""
ACCORDING TO THE WEBSITE THAT PROVIDED THIS DATASET, THE FILE IS ALREADY CLEANED UP AND READY TO BE 
USED FOR MACHINE LEARNING AND VISUALISATION. I JUST NEED TO ADD A FEW MEASURE COLUMNS AND IT WILL BE READY TO USE FOR MY PROJECT TOO
"""

'\nACCORDING TO THE WEBSITE THAT PROVIDED THIS DATASET, THE FILE IS ALREADY CLEANED UP AND READY TO BE \nUSED FOR MACHINE LEARNING AND VISUALISATION\n'

In [3]:
df["date"] = pd.to_datetime(df["date"])

In [4]:
current_year = 2026
df['house_age'] = current_year - df['yr_built']

In [12]:
df['has_basement'] = df['sqft_basement'].apply(lambda x: True if x > 0 else False)

In [13]:
df['is_renovated'] = df['yr_renovated'].apply(lambda x: True if x > 0 else False)

In [18]:
def calculate_estimated_price(row):

    base_price = row['sqft_living'] * row['price_per_sqft']

    condition_multiplier = 1 + (row['condition'] - 3) * 0.05
    
    age_discount = max(0, row['house_age'] * 0.002)

    waterfront_bonus = 0.30 if row['waterfront'] == 1 else 0.0

    adjusted_price = base_price * condition_multiplier * (1 - age_discount) * (1 + waterfront_bonus)

    return round(adjusted_price, 2)


df['estimate_price'] = df.apply(calculate_estimated_price, axis=1)

In [19]:
df.loc[2].to_frame()

                                       2
date                 2014-05-02 00:00:00
price                           342000.0
bedrooms                             3.0
bathrooms                            2.0
sqft_living                         1930
sqft_lot                           11947
floors                               1.0
waterfront                             0
view                                   0
condition                              4
sqft_above                          1930
sqft_basement                          0
yr_built                            1966
yr_renovated                           0
street          26206-26214 143rd Ave SE
city                                Kent
statezip                        WA 98042
price_per_sqft                     177.2
house_age                             60
has_basement                       False
is_renovated                       False
estimate_price                  316004.3

In [20]:
df.to_csv("cleaned_housesales_data.csv", index=False)

In [21]:
df.describe()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft,house_age,estimate_price
count,4600,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4.600000e+03
mean,2014-06-07 03:14:42.782608,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261,265.876209,55.213696,5.057167e+05
min,2014-05-02 00:00:00,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000,0.000000,12.000000,0.000000e+00
25%,2014-05-21 00:00:00,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000,180.817500,29.000000,2.931396e+05
50%,2014-06-09 00:00:00,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000,243.855000,50.000000,4.165844e+05
75%,2014-06-24 00:00:00,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000,314.840000,75.000000,5.969310e+05
max,2014-07-10 00:00:00,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000,22533.900000,126.000000,2.602098e+07
std,NaN,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536,357.503362,29.731848,5.426281e+05