In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
from matplotlib.ticker import FuncFormatter


df = pd.read_csv('students_data.csv')

In [3]:
df.shape

(100000, 33)

In [4]:
df.columns

Index(['student_id', 'age', 'gender', 'education_level', 'school_type',
       'family_income', 'parent_education', 'previous_exam_score',
       'previous_gpa', 'assignment_completion_rate', 'class_participation',
       'study_hours_per_day', 'self_study_hours', 'private_tuition',
       'study_consistency', 'study_environment', 'revision_frequency',
       'practice_tests_completed', 'sleep_hours', 'daily_screen_time',
       'physical_activity_hours', 'stress_level', 'internet_access',
       'exam_difficulty', 'exam_preparation_days', 'questions_attempted',
       'questions_correct', 'time_management_score', 'exam_anxiety_level',
       'exam_score', 'performance_grade', 'pass_status', 'performance_level'],
      dtype='str')

In [24]:
df = df.apply(lambda col: col.str.strip().str.lower() if col.dtype == "object" else col)

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [27]:
df['student_id'].is_unique

True

In [28]:
df.isna().sum()

student_id                    0
age                           0
gender                        0
education_level               0
school_type                   0
family_income                 0
parent_education              0
previous_exam_score           0
previous_gpa                  0
assignment_completion_rate    0
class_participation           0
study_hours_per_day           0
self_study_hours              0
private_tuition               0
study_consistency             0
study_environment             0
revision_frequency            0
practice_tests_completed      0
sleep_hours                   0
daily_screen_time             0
physical_activity_hours       0
stress_level                  0
internet_access               0
exam_difficulty               0
exam_preparation_days         0
questions_attempted           0
questions_correct             0
time_management_score         0
exam_anxiety_level            0
exam_score                    0
performance_grade             0
pass_status                   0
performance_level             0
dtype: int64

In [29]:
df.dtypes

student_id                        str
age                             int64
gender                            str
education_level                   str
school_type                       str
family_income                     str
parent_education                  str
previous_exam_score           float64
previous_gpa                  float64
assignment_completion_rate    float64
class_participation               str
study_hours_per_day           float64
self_study_hours              float64
private_tuition                 int64
study_consistency                 str
study_environment                 str
revision_frequency                str
practice_tests_completed        int64
sleep_hours                   float64
daily_screen_time             float64
physical_activity_hours       float64
stress_level                    int64
internet_access                 int64
exam_difficulty                   str
exam_preparation_days           int64
questions_attempted             int64
questions_correct               int64
time_management_score         float64
exam_anxiety_level            float64
exam_score                    float64
performance_grade                 str
pass_status                       str
performance_level                 str
dtype: object

In [31]:
#checking impossible values
df.select_dtypes("number").describe()

,age,previous_exam_score,previous_gpa,assignment_completion_rate,study_hours_per_day,self_study_hours,private_tuition,practice_tests_completed,sleep_hours,daily_screen_time,physical_activity_hours,stress_level,internet_access,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,17.005740,69.531033,2.780823,69.724405,2.995725,2.094970,0.299800,5.509170,6.995102,5.000495,2.487579,9.375640,0.918760,15.501440,92.492150,57.298240,78.456368,8.927373,61.950072
std,1.999562,11.379108,0.459206,12.127179,1.719466,1.266066,0.458173,2.501131,1.200874,1.775716,2.413386,1.081613,0.273205,8.644356,4.609376,15.028787,13.411229,1.354875,15.863644
min,14.000000,30.000000,1.000000,20.000000,0.500000,0.250000,0.000000,0.000000,3.000000,1.000000,0.000000,5.000000,0.000000,1.000000,85.000000,0.000000,17.030000,1.000000,0.000000
25%,15.000000,61.820000,2.490000,61.480000,1.720000,1.170000,0.000000,4.000000,6.180000,3.770000,0.720000,9.000000,1.000000,8.000000,88.000000,47.000000,69.990000,8.220000,51.240000
50%,17.000000,69.530000,2.780000,69.570000,2.670000,1.840000,0.000000,5.000000,7.000000,4.990000,1.730000,10.000000,1.000000,16.000000,92.000000,57.000000,79.000000,9.490000,61.960000
75%,19.000000,77.232500,3.070000,77.920000,3.910000,2.730000,1.000000,7.000000,7.810000,6.210000,3.480000,10.000000,1.000000,23.000000,96.000000,67.000000,87.980000,10.000000,72.730000
max,20.000000,100.000000,4.000000,100.000000,12.000000,10.000000,1.000000,20.000000,11.000000,12.080000,12.000000,10.000000,1.000000,30.000000,100.000000,100.000000,100.000000,10.000000,100.000000

In [34]:
str_cols = df.select_dtypes(include="object").columns

unique_table = pd.DataFrame({
    "column": str_cols,
    "unique_values": [
        df[col].dropna().unique().tolist()
        for col in str_cols
    ]
})

unique_table

C:\Users\user\AppData\Local\Temp\ipykernel_15664\1379116126.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include="object").columns

                 column                                      unique_values
0            student_id  [STU_000001, STU_000002, STU_000003, STU_00000...
1                gender                              [Female, Male, Other]
2       education_level                       [High School, Undergraduate]
3           school_type                         [Public, Private, Charter]
4         family_income    [Middle, High, Lower-Middle, Upper-Middle, Low]
5      parent_education  [Unknown, Master, High School, Bachelor, Assoc...
6   class_participation                                [Medium, Low, High]
7     study_consistency                                [Medium, Low, High]
8     study_environment                           [Moderate, Quiet, Noisy]
9    revision_frequency                            [Rarely, Daily, Weekly]
10      exam_difficulty                               [Medium, Easy, Hard]
11    performance_grade                                    [A, B, D, C, F]
12          pass_status                                       [Pass, Fail]
13    performance_level                                [High, Medium, Low]

In [38]:
#nothing really to import to a new file, i'll use this raw file itself for analysis.