In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
from matplotlib.ticker import FuncFormatter


df = pd.read_csv('student_exam_performance.csv')

In [3]:
df.shape

(100000, 44)

In [4]:
df.columns

Index(['student_id', 'age', 'gender', 'education_level', 'school_type',
       'family_income', 'parent_education', 'urban_rural',
       'previous_exam_score', 'previous_gpa', 'attendance_percentage',
       'assignment_completion_rate', 'class_participation',
       'study_hours_per_day', 'self_study_hours', 'private_tuition',
       'online_learning_hours', 'study_consistency', 'study_environment',
       'study_method', 'revision_frequency', 'practice_tests_completed',
       'notes_quality', 'sleep_hours', 'sleep_quality', 'daily_screen_time',
       'physical_activity_hours', 'break_frequency', 'stress_level',
       'motivation_level', 'internet_access', 'device_availability',
       'educational_app_usage', 'online_course_hours', 'exam_difficulty',
       'exam_preparation_days', 'questions_attempted', 'questions_correct',
       'time_management_score', 'exam_anxiety_level', 'exam_score',
       'performance_grade', 'pass_status', 'performance_level'],
      dtype='str')

In [5]:
#removing unnecessary and extreme niche columns for my project

df = df.drop(columns=[
    "urban_rural",
    "attendance_percentage",
    "online_learning_hours",
    "study_method",
    "notes_quality",
    "sleep_quality",
    "break_frequency",
    "motivation_level",
    "educational_app_usage",
    "online_course_hours",
    "device_availability"
])

In [6]:
df.head(2)

,student_id,age,gender,education_level,school_type,family_income,parent_education,previous_exam_score,previous_gpa,assignment_completion_rate,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,78.36,2.95,65.18,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,73.40,2.89,76.53,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High

In [7]:
#checking impossible values
df.describe()

,age,previous_exam_score,previous_gpa,assignment_completion_rate,study_hours_per_day,self_study_hours,private_tuition,practice_tests_completed,sleep_hours,daily_screen_time,physical_activity_hours,stress_level,internet_access,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score
count,100000.000000,100000.000000,92207.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,90387.000000,100000.000000,100000.000000
mean,17.005740,69.531033,2.780892,69.724405,2.995725,2.094970,0.299800,5.509170,6.995102,5.000495,2.487579,9.375640,0.918760,15.501440,92.492150,57.298240,78.398551,8.927373,61.950072
std,1.999562,11.379108,0.478218,12.127179,1.719466,1.266066,0.458173,2.501131,1.200874,1.775716,2.413386,1.081613,0.273205,8.644356,4.609376,15.028787,14.105155,1.354875,15.863644
min,14.000000,30.000000,1.000000,20.000000,0.500000,0.250000,0.000000,0.000000,3.000000,1.000000,0.000000,5.000000,0.000000,1.000000,85.000000,0.000000,17.030000,1.000000,0.000000
25%,15.000000,61.820000,2.460000,61.480000,1.720000,1.170000,0.000000,4.000000,6.180000,3.770000,0.720000,9.000000,1.000000,8.000000,88.000000,47.000000,68.790000,8.220000,51.240000
50%,17.000000,69.530000,2.780000,69.570000,2.670000,1.840000,0.000000,5.000000,7.000000,4.990000,1.730000,10.000000,1.000000,16.000000,92.000000,57.000000,79.000000,9.490000,61.960000
75%,19.000000,77.232500,3.110000,77.920000,3.910000,2.730000,1.000000,7.000000,7.810000,6.210000,3.480000,10.000000,1.000000,23.000000,96.000000,67.000000,89.210000,10.000000,72.730000
max,20.000000,100.000000,4.000000,100.000000,12.000000,10.000000,1.000000,20.000000,11.000000,12.080000,12.000000,10.000000,1.000000,30.000000,100.000000,100.000000,100.000000,10.000000,100.000000

In [8]:
#checking if incorrect data types
df.dtypes

student_id                        str
age                             int64
gender                            str
education_level                   str
school_type                       str
family_income                     str
parent_education                  str
previous_exam_score           float64
previous_gpa                  float64
assignment_completion_rate    float64
class_participation               str
study_hours_per_day           float64
self_study_hours              float64
private_tuition                 int64
study_consistency                 str
study_environment                 str
revision_frequency                str
practice_tests_completed        int64
sleep_hours                   float64
daily_screen_time             float64
physical_activity_hours       float64
stress_level                    int64
internet_access                 int64
exam_difficulty                   str
exam_preparation_days           int64
questions_attempted             int64
questions_correct               int64
time_management_score         float64
exam_anxiety_level            float64
exam_score                    float64
performance_grade                 str
pass_status                       str
performance_level                 str
dtype: object

In [9]:
df.isna().sum()

student_id                       0
age                              0
gender                           0
education_level                  0
school_type                      0
family_income                    0
parent_education              6526
previous_exam_score              0
previous_gpa                  7793
assignment_completion_rate       0
class_participation              0
study_hours_per_day              0
self_study_hours                 0
private_tuition                  0
study_consistency                0
study_environment                0
revision_frequency               0
practice_tests_completed         0
sleep_hours                      0
daily_screen_time                0
physical_activity_hours          0
stress_level                     0
internet_access                  0
exam_difficulty                  0
exam_preparation_days            0
questions_attempted              0
questions_correct                0
time_management_score         9613
exam_anxiety_level               0
exam_score                       0
performance_grade                0
pass_status                      0
performance_level                0
dtype: int64

In [10]:
df['student_id'].is_unique

True

In [11]:
df.duplicated().sum()
df = df.drop_duplicates()

In [12]:
df.select_dtypes(include="object").apply(lambda x: x.unique())

C:\Users\user\AppData\Local\Temp\ipykernel_7328\3056900651.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").apply(lambda x: x.unique())

student_id             [STU_000001, STU_000002, STU_000003, STU_00000...
gender                                             [Female, Male, Other]
education_level                             [High School, Undergraduate]
school_type                                   [Public, Private, Charter]
family_income            [Middle, High, Lower-Middle, Upper-Middle, Low]
parent_education       [nan, Master, High School, Bachelor, Associate...
class_participation                                  [Medium, Low, High]
study_consistency                                    [Medium, Low, High]
study_environment                               [Moderate, Quiet, Noisy]
revision_frequency                               [Rarely, Daily, Weekly]
exam_difficulty                                     [Medium, Easy, Hard]
performance_grade                                        [A, B, D, C, F]
pass_status                                                 [Pass, Fail]
performance_level                                    [High, Medium, Low]
dtype: object

In [13]:
df["parent_education"] = df["parent_education"].fillna("Unknown")
df['parent_education'].value_counts()

parent_education
High School    28122
Bachelor       27943
Associate      18640
Master         14043
Unknown         6526
Doctorate       4726
Name: count, dtype: int64

In [14]:
#pct of the empy values in these two columns

df[["previous_gpa", "time_management_score"]].isna().mean() * 100

previous_gpa             7.793
time_management_score    9.613
dtype: float64

In [15]:
df["previous_gpa"] = df["previous_gpa"].fillna(df["previous_gpa"].median())

df["time_management_score"] = df["time_management_score"].fillna(
    df["time_management_score"].median()
)

In [16]:
df.to_csv("cleaned_student_data.csv", index=False)